services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes:
      - .:/usr/src/app:Z
    ports:
      - "4000:4000"
    userns_mode: keep-id
    environment:
      JEKYLL_ENV: docker
    command: jekyll serve -H 0.0.0.0 -w --config _config.yml,_config_docker.yml